server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 1.开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh
          #          uri:  http://localhost:8001 # 匹配后提供服务的路由地址
          uri:  lb://CLOUD-PROVIDER-PAYMENT-SERVICE # 2.输入服务名，lb代表负载均衡
          predicates:
            - Path=/payment/get/**

        - id: payment_routh2
          #          uri:  http://localhost:8001 # 匹配后提供服务的路由地址
          uri:  lb://CLOUD-PROVIDER-PAYMENT-SERVICE # 2.输入服务名，lb代表负载均衡
          predicates:
            - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka:  true
      fetch-registry:  true
      defaultZone: http://eureka7001.com:7001/eureka